# Generated by Django 4.0 on 2022-01-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entreprise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='anneeCreation',
            field=models.IntegerField(null=True),
        ),
    ]
