# Generated by Django 4.0 on 2022-01-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employé',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomEmploye', models.CharField(max_length=50, null=True)),
                ('prenomEmploye', models.CharField(max_length=50, null=True)),
                ('dateNaissance', models.DateField(auto_now_add=True, null=True)),
                ('lieuNaissance', models.CharField(max_length=50, null=True)),
                ('nationalite', models.CharField(choices=[('Allemande', 'Allemande'), ('Américaine', 'Américaine'), ('Anglaise', 'Anglaise'), ('Belge', 'Belge'), ('Chinoise', 'Chinoise'), ('Cubaine', 'Cubaine'), ('Danoise', 'Danoise'), ('Espagnole', 'Espagnole'), ('Française', 'Française'), ('Hongrois', 'Hongrois'), ('Italienne', 'Italienne'), ('Japonaise', 'Japonaise'), ('Marocaine', 'Marocaine'), ('Mexicaine', 'Mexicaine'), ('Norvégien', 'Norvégien'), ('Philippine', 'Philippine'), ('Russe', 'Russe'), ('Sénégalaise', 'Sénégalaise'), ('Suédoise', 'Suédoise'), ('Tunisienne', 'Tunisienne'), ('Vietnamienne', 'Vietnamienne')], max_length=50, null=True)),
                ('statusMatrimonial', models.CharField(choices=[('Marié(e)', 'Marié(e)'), ('Célibataire', 'Célibataire'), ('Divorsé(e)', 'Divorsé(e)')], max_length=50, null=True)),
                ('fonction', models.CharField(max_length=50, null=True)),
                ('typeContrat', models.CharField(max_length=50, null=True)),
                ('dateRecrutement', models.DateField(auto_now_add=True, null=True)),
                ('dateFin', models.DateField(auto_now_add=True, null=True)),
                ('salaireBase', models.IntegerField(null=True)),
                ('salaireNet', models.IntegerField(null=True)),
            ],
        ),
    ]
