# Generated by Django 4.0 on 2022-01-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employé', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employé',
            name='nationalite',
            field=models.CharField(choices=[('Allemande', 'Allemande'), ('Algérien', 'Algérien'), ('Angolais', 'Angolais'), ('Argentin', 'Argentin'), ('Américaine', 'Américaine'), ('Anglaise', 'Anglaise'), ('Australien', 'Australien'), ('Autrichien', 'Autrichien'), ('Bahamien', 'Bahamien'), ('Belge', 'Belge'), ('Béninois', 'Béninois'), ('Bisseau-Guinéen', 'Bisseau-Guinéen'), ('Brésilien', 'Brésilien'), ('Burkinabé', 'Burkinabé'), ('Burundi', 'Burundi'), ('Camerounaise', 'Camerounaise'), ('Canadienne', 'Canadienne'), ('Chilien', 'Chilien'), ('Chinois', 'Chinois'), ('Colombien', 'Colombien'), ('Congolais', 'Congolais'), ('Corée du sud', 'Corée du sud'), ('Coréen', 'Coréen'), ('Cubain', 'Cubain'), ('Danois', 'Danois'), ('Egyptien', 'Egyptien'), ('Equatorien', 'Equatorien'), ('Espagnole', 'Espagnole'), ('Estonien', 'Estonien'), ('Etyiopien', 'Etyiopien'), ('Finlandais', 'Finlandais'), ('Française', 'Française'), ('Gabonais', 'Gabonais'), ('gambien', 'gambien'), ('ghanéen', 'ghanéen'), ('Grec', 'Grec'), ('Guinéenne', 'Guinéenne'), ('Haïtien', 'Haïtien'), ('Hongrois', 'Hongrois'), ('Indien', 'Indien'), ('Indonésien', 'Indonésien'), ('Irlandais', 'Irlandais'), ('Islandais', 'Islandais'), ('Israélien', 'Israélien'), ('Italien', 'Italien'), ('Ivoirien', 'Ivoirien'), ('Jamaïquain', 'Jamaïquain'), ('Japonais', 'Japonais'), ('Jordanien', 'Jordanien'), ('Kényen', 'Kényen'), ('Libye', 'Libye'), ('Marocain', 'Marocain'), ('Mexicain', 'Mexicain'), ('Motswanan', 'Motswanan'), ('Mozambique', 'Mozambique'), ('Namibie', 'Namibie'), ('Nigeria', 'Nigeria'), ('Nigérien', 'Nigérien'), ('Norvégien', 'Norvégien'), ('Pakistanais', 'Pakistanais'), ('Palestinien', 'Palestinien'), ('Péruvien', 'Péruvien'), ('Philippin', 'Philippin'), ('Polonais', 'Polonais'), ('Portugais', 'Portugais'), ('Québécois', 'Québécois'), ('Roumain', 'Roumain'), ('Russe', 'Russe'), ('Sénégalais', 'Sénégalais'), ('Suédois', 'Suédois'), ('Tchadien', 'Tchadien'), ('Tchèque', 'Tchèque'), ('Tunisienne', 'Tunisienne'), ('Vietnamienne', 'Vietnamienne'), ('Zambien', 'Zambien'), ('Zimbabwéen', 'Zimbabwéen')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employé',
            name='typeContrat',
            field=models.CharField(choices=[('Durée déterminée', 'Durée déterminée'), ('Durée indéterminée', 'Durée indéterminée')], max_length=50, null=True),
        ),
    ]
